---
title: "Incidents - Non-Standard Algorithm"
author: "Lex Gourley"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
require(data.table)
require(ggplot2)
require(MASS)
require(tidyverse)
require(janitor)
require(chron)
require(stringr)
require(tm)
require(qdap)

knitr::opts_knit$set(root.dir = "C://Users//maygo//OneDrive//Documents//DAEN690-FAA-UAS//DATA")
```

```{r read}
#enter name of file
file <- "3.2.2.2 - ExceptionFile_Standard_415OUTOF543.csv" 
# airport <- read.csv("00 - Airports.csv",header = TRUE, stringsAsFactors = FALSE, na.strings=c("NA","N/A","","na","Na","n/a","N/a","NaN","nA"))
# navaid <- read.csv("00 - Navaid.csv",header = TRUE, stringsAsFactors = FALSE, na.strings=c("NA","N/A","","na","Na","n/a","N/a","NaN","nA"))
filename <- gsub(pattern="\\.csv$","",file)
df <- read.csv(file,header = TRUE, stringsAsFactors = FALSE, na.strings=c("NA","N/A","","na","Na","n/a","N/a","NaN","nA"))
setDT(df)

#standardize dataset
df$REMARKS <- gsub("(Runway|runway|RUNWAY)","RWY",df$REMARKS)
df$REMARKS <- gsub("RY","RWY",df$REMARKS)
df$REMARKS <- gsub("of the","of",df$REMARKS)
df$REMARKS <- gsub("(M|m)iles?","NM",df$REMARKS)
df$SUMMARY.CEDAR <- gsub("(M|m)iles?","NM",df$SUMMARY.CEDAR)
df$REMARKS <- gsub("UAS","uas",df$REMARKS)
df$REMARKS <- gsub("(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}","",df$REMARKS)

df$REMARKS <- gsub("(NM)([A-Z]{1,3})","\\1 \\2",df$REMARKS)
df$REMARKS <- gsub("([0-9]*\\-*\\/*[0-9]*\\.*[0-9]\\.*[0-9]*)(\\NM)","\\1 \\2",df$REMARKS)
df$REMARKS <- gsub("(of)([A-Z]{3,4})","\\1 \\2",df$REMARKS)
df$REMARKS <- gsub("([A-Z]{1,3})(of)","\\1 \\2",df$REMARKS)
df$REMARKS <- gsub("([A-Z]{1,3})(\\s[A-Z]{3,4}$)","\\1 of\\2",df$REMARKS)
df$REMARKS <- gsub("(RWY)([0-9]{1,2}[L|R|C]?)","\\1 \\2",df$REMARKS)
df$REMARKS <- gsub("(RWY\\s)(\\d(?!\\d))","\\10\\2",df$REMARKS,perl=T)
df$REMARKS <- gsub("  "," ",df$REMARKS)
df$REMARKS <- gsub("south","S",df$REMARKS)
df$REMARKS <- gsub("east","E",df$REMARKS)
df$REMARKS <- gsub("north","N",df$REMARKS)
df$REMARKS <- gsub("west","W",df$REMARKS)
df$REMARKS <- gsub("South","S",df$REMARKS)
df$REMARKS <- gsub("East","E",df$REMARKS)
df$REMARKS <- gsub("North","N",df$REMARKS)
df$REMARKS <- gsub("West","W",df$REMARKS)

# uas lat/long from cedar
df_uaslatlong <- df[!is.na(df$UASLAT.CEDAR)]
df_uaslatlong$DATASET <- "LAT/LONG"
df_uaslatlong$UASLOCATION <- NA

# remove FRZ
df_2 <- df[is.na(df$UASLAT.CEDAR)]
df_frz <- df_2[grep("FRZ",df_2$REMARKS)]
df_frz$DATASET <- "FRZ"

#extract all designated points
df_3 <- df_2[!grep("FRZ",df_2$REMARKS)]
df_3$UASLOCATION <- str_extract(df_3$REMARKS,'[0-9]*[.|-|/]*[0-9]*\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)([A-Z]{5})')
df_dp <- df_3[!is.na(df_3$UASLOCATION)]
df_dp$DATASET <- "DESIGNATED POINT"
df_dp_dups <- df_dp[duplicated(df_dp[,c("dateonly","UASLOCATION")]),]
df_dp <- distinct(df_dp,dateonly,UASLOCATION,.keep_all=TRUE)

#extract all navaid
pattern <- c("VOR","vor","NDB","ndb")
df_3 <- df_3[is.na(df_3$UASLOCATION)]
df_4 <- df_3[grep(paste(pattern,collapse="|"),df_3$REMARKS)]
df_4$DATASET <- "NAVAID"
df_4$UASLOCATION <- str_extract(df_4$REMARKS,'[0-9]*[.|-|/]*[0-9]*\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_navaid <- df_4[!is.na(df_4$UASLOCATION)]
df_navaid <- distinct(df_navaid,dateonly,UASLOCATION,.keep_all=TRUE)
df_navaid_na <- df_4[is.na(df_4$UASLOCATION)]
df_navaid_na$UASLOCATION <- df_navaid_na$REPORTINGFACILITY
df_navaid_dups <- df_navaid_na[duplicated(df_navaid_na[,c("dateonly","UASLOCATION")]),]
df_navaid_na <- distinct(df_navaid_na,dateonly,UASLOCATION,.keep_all=TRUE)

#extract all runway
df_5 <- df_3[!grep(paste(pattern,collapse="|"),df_3$REMARKS)]
df_5$RWYLOCATION <- str_extract(df_5$REMARKS,'RWY\\s?[0-9]{1,2}[L|R|C]?')
df_rwy <- df_5[!is.na(df_5$RWYLOCATION)]
df_rwy$UASLOCATION <- str_extract(df_rwy$REMARKS,'([0-9]*[.|-|/]*[0-9]*)\\s*(nm|NM)\\s*(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_52 <- df_rwy[is.na(df_rwy$UASLOCATION)]
df_52$UASLOCATION <- str_extract(df_52$REMARKS,'([0-9]*[.|-|/]*[0-9]*)\\s*(nm|NM)\\s*(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?)')
df_rwy2 <- df_52[!is.na(df_52$UASLOCATION)]
df_rwy2$UASLOCATION <- paste(df_rwy2$UASLOCATION,df_rwy2$REPORTINGFACILITY)
df_rwy_na <- df_52[is.na(df_52$UASLOCATION)]
df_rwy_na$UASLOCATION <- df_rwy_na$REPORTINGFACILITY
df_rwy <- df_rwy[!is.na(df_rwy$UASLOCATION)]
df_rwy$DATASET <- "RUNWAY"
df_rwy <- rbind(df_rwy,df_rwy2)
df_rwy_dups <- df_rwy[duplicated(df_rwy[,c("dateonly","UASLOCATION")]),]
df_rwy <- distinct(df_rwy,dateonly,UASLOCATION,.keep_all=TRUE)

#extract all airports
df_6 <- df_5[is.na(df_5$RWYLOCATION)]
df_6$UASLOCATION <- str_extract(df_6$REMARKS,'[0-9]*[.|-|/]*[0-9]*\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_airport <- df_6[!is.na(df_6$UASLOCATION)]
df_6 <- df_6[is.na(df_6$UASLOCATION)]
df_6$UASLOCATION <- str_extract(df_6$REMARKS,'\\b\\d[.|-|/]*\\d*\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)* (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_airport2 <- df_6[!is.na(df_6$UASLOCATION)]
df_airport2$UASLOCATION <- gsub("(\\d[.|-|/]*\\d*\\s)(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)","\\1NM \\2",df_airport2$UASLOCATION)
df_airport <- rbind(df_airport,df_airport2)
df_airport$DATASET <- "AIRPORT"
df_airport_dups <- df_airport[duplicated(df_airport[,c("dateonly","UASLOCATION")]),]
df_airport <- distinct(df_airport,dateonly,UASLOCATION,.keep_all=TRUE)

# fixed radial distance
df_7 <- df_6[is.na(df_6$UASLOCATION)]
df_7$UASLOCATION <- str_extract(df_7$REMARKS,'[A-Z]{3}\\d{6}')
df_frd <- df_7[!is.na(df_7$UASLOCATION)]
df_frd$location <- str_extract(df_frd$UASLOCATION,'^[A-Z]{3}')
df_frd$heading <- str_extract(df_frd$UASLOCATION,'[0-9]{3}([0-9]{3})$')
df_frd$heading <- str_extract(df_frd$heading,'^[0-9]{3}')
df_frd$nm <- str_extract(df_frd$UASLOCATION,'[0-9]{3}$')
df_frd$UASLOCATION <- paste(df_frd$nm,"NM",df_frd$heading,"of",df_frd$location)
df_frd$DATASET <- "FIX RADIAL"
df_frd <- df_frd[,c("location","heading","nm"):=NULL]
df_frd_dups <- df_frd[duplicated(df_frd[,c("dateonly","UASLOCATION")]),]
df_frd <- distinct(df_frd,dateonly,UASLOCATION,.keep_all=TRUE)

# pull out city names
df_8 <- df_7[is.na(df_7$UASLOCATION)]
df_8$UASLOCATION <- str_extract(df_8$REMARKS,'[0-9]*[.|-|/]*[0-9]\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)(\\w+)(\\,|\\.)')
df_8$cityname <- str_extract(df_8$UASLOCATION,'\\w+(\\,|\\.)$')
df_8$cityname <- str_extract(df_8$cityname,'^\\D+()')
df_8$cityname <- str_extract(df_8$cityname,'^\\w+()')
df_8$cityname <- gsub('\\b\\w{1,3}\\b',NA,df_8$cityname)
df_8$UASLOCATION <- str_extract(df_8$UASLOCATION,'[0-9]*[.|-|/]*[0-9]\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)')
df_city <- df_8[!is.na(df_8$cityname)]
df_city$DATASET <- "CITY"
df_city_dups <- df_city[duplicated(df_city[,c("dateonly","UASLOCATION")]),]
df_city <- distinct(df_city,dateonly,UASLOCATION,.keep_all=TRUE)


#extract all airports - CEDAR
df_9 <- df_8[is.na(df_8$cityname)]
df_9$UASLOCATION <- str_extract(df_9$SUMMARY.CEDAR,'[0-9]*[.|-|/]*[0-9]*\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_cedarair <- df_9[!is.na(df_9$UASLOCATION)]
df_9 <- df_9[is.na(df_9$UASLOCATION)]
df_9$UASLOCATION <- str_extract(df_9$SUMMARY.CEDAR,'\\b\\d[.|-|/]*\\d*\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)* (\\s?(of|OF)?\\s?)([A-Z]{3})')
df_cedarair2 <- df_9[!is.na(df_9$UASLOCATION)]
df_cedarair2$UASLOCATION <- gsub("(\\d[.|-|/]*\\d*\\s?)(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)","\\1NM \\2",df_cedarair2$UASLOCATION)
df_cedarair <- rbind(df_cedarair,df_cedarair2)
df_cedarair$DATASET <- "AIRPORT - CEDAR"
df_cedarair_dups <- df_cedarair[duplicated(df_cedarair[,c("dateonly","UASLOCATION")]),]
df_cedarair <- distinct(df_cedarair,dateonly,UASLOCATION,.keep_all=TRUE)

# fixed radial distance - CEDAR
df_10 <- df_9[is.na(df_9$UASLOCATION)]
df_10$UASLOCATION <- str_extract(df_10$SUMMARY.CEDAR,'[A-Z]{3}\\d{6}')
df_cedarfrd <- df_10[!is.na(df_10$UASLOCATION)]
df_cedarfrd$location <- str_extract(df_cedarfrd$UASLOCATION,'^[A-Z]{3}')
df_cedarfrd$heading <- str_extract(df_cedarfrd$UASLOCATION,'[0-9]{3}([0-9]{3})$')
df_cedarfrd$heading <- str_extract(df_cedarfrd$heading,'^[0-9]{3}')
df_cedarfrd$nm <- str_extract(df_cedarfrd$UASLOCATION,'[0-9]{3}$')
df_cedarfrd$UASLOCATION <- paste(df_cedarfrd$nm,"NM",df_cedarfrd$heading,"of",df_cedarfrd$location)
df_cedarfrd$DATASET <- "FIX RADIAL - CEDAR"
df_cedarfrd <- df_cedarfrd[,c("location","heading","nm"):=NULL]
df_cedarfrd_dups <- df_cedarfrd[duplicated(df_cedarfrd[,c("dateonly","UASLOCATION")]),]
df_cedarfrd <- distinct(df_cedarfrd,dateonly,UASLOCATION,.keep_all=TRUE)

#extract all else
df_11 <- df_10[is.na(df_10$cityname)]
df_11$UASLOCATION <- str_extract(df_11$REMARKS,'[0-9]*[.|-|/]*[0-9]*\\s?(nm|NM)\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?)')
df_unk <- df_11[!is.na(df_11$UASLOCATION)]
df_unk$UASLOCATION <- paste(df_unk$UASLOCATION,df_unk$REPORTINGFACILITY)
df_11 <- df_11[is.na(df_11$UASLOCATION)]
df_11$UASLOCATION <- str_extract(df_11$REMARKS,'\\d[.|-|/]*\\d*\\s?(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW) (\\s?(of|OF)?\\s?)')
df_repfac <- df_11[!is.na(df_11$UASLOCATION)]
df_repfac$UASLOCATION <- gsub("(\\d[.|-|/]*\\d*\\s?)(N|S|E|W|NW|NE|SW|SE|SSE|SSW|SNE|SNW|NNE|NSE|NNE|NNW|WSW|WNW|WSE|WNE|ENE|ESE|ESW|ENW)","\\1NM \\2",df_repfac$UASLOCATION)
df_repfac$UASLOCATION <- paste(df_repfac$UASLOCATION,df_repfac$REPORTINGFACILITY)
df_unk <- rbind(df_unk,df_repfac)
df_unk$DATASET <- "AIRPORT(?)"
df_unk_dups <- df_unk[duplicated(df_unk[,c("dateonly","UASLOCATION")]),]
df_unk <- distinct(df_unk,dateonly,UASLOCATION,.keep_all=TRUE)

df_unk_na <- df_11[is.na(df_11$UASLOCATION)]
df_unk_na$UASLOCATION <- df_unk_na$REPORTINGFACILITY
df_unk_na$DATASET <- "EXCEPTION"
df_exp <- rbind(df_unk,df_unk_na,df_navaid_na,df_rwy_na,df_frz,fill=TRUE)
df_dupes <- rbind(df_airport_dups,df_dp_dups,df_frd_dups,df_navaid_dups,df_rwy_dups,df_city_dups,df_cedarair_dups,df_cedarfrd_dups,fill=TRUE)
df_all <- rbind(df_navaid,df_rwy,df_dp,df_airport,df_frd,df_uaslatlong,df_city,df_cedarair,df_cedarfrd,fill=TRUE)
df_all <- arrange(df_all,DATE)

write.csv(df_exp,paste("Output_ExceptionFile_",filename,".csv",sep=""),row.names=FALSE)
write.csv(df_all,paste("Output_All_Points_",filename,".csv",sep=""),row.names=FALSE)
write.csv(df_dupes,paste("Output_Duplicates_",filename,".csv",sep=""),row.names=FALSE)

```